spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  application:
    name: micro-service-oauth-order
server:
  port: 6100
  servlet:
    context-path: /client-order

security:
  oauth2:
    client:
      client-id: order-client
      client-secret: order-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: dev
    authorization:
      check-token-access: http://localhost:6001/oauth/check_token
