DECLARE

V_SQL_VD10003 VARCHAR2(4000);
V_SQL_VD10004 VARCHAR2(4000);

BEGIN

V_SQL_VD10003:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD10003 AS
SELECT T.ELE_CODE AS GUID,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.ELE_CATALOG_ID,
       T.MOF_DIV_CODE AS PROVINCE,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED,
       T.UPDATE_TIME,
       T.IS_DELETED,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.FISCAL_YEAR AS YEAR,
       T.FUND_TYPE_CODE,
       T.ZJXZ
  FROM ELE_VD10003 T, ELE_VD10003 T1
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';
V_SQL_VD10004:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD10004 AS
SELECT T.FUNCTYPE,
       T.ELE_CODE AS GUID,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.ELE_CATALOG_ID,
       T.MOF_DIV_CODE AS PROVINCE,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED STATUS,
       T.UPDATE_TIME,
       T.IS_DELETED,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.FISCAL_YEAR,
       T.FISCAL_YEAR AS YEAR,
       T.FUND_TYPE_CODE,
       T.ZJXZ
  FROM ELE_VD10004 T, ELE_VD10004 T1
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';
EXECUTE IMMEDIATE V_SQL_VD10003;
EXECUTE IMMEDIATE V_SQL_VD10004;
END;










