DECLARE
V_SQL_VD00010 VARCHAR2(4000);
V_SQL_VD09001 VARCHAR2(4000);
V_SQL_VD10003 VARCHAR2(4000);
V_SQL_VD10004 VARCHAR2(4000);
V_SQL_VC01004 VARCHAR2(4000);
V_SQL_VD08001 VARCHAR2(4000);
BEGIN
V_SQL_VD00010:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD00010 AS
SELECT T.ELE_CODE AS GUID,
       ELE_CODE AS CODE,
       ELE_NAME AS NAME,
       '8700XJ0KTNQH' AS ELE_CATALOG_ID,
       'VD00010' AS ELE_CATALOG_CODE,
       MOF_DIV_CODE AS PROVINCE,
       (SELECT ELE_CODE
          FROM ELE_VD00010 F
         WHERE F.FISCAL_YEAR = T.FISCAL_YEAR
           AND F.MOF_DIV_CODE = T.MOF_DIV_CODE
           AND F.ELE_ID = T.PARENT_ID) AS SUPERGUID,
       LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       ADMDIV,
       REMARK,
       ORGSPEC,
       ZIP,
       VERSION,
       TEL,
       INTORG,
       FAX,
       SRCGUID,
       DESGUID,
       ADDRESS,
       SRCSCALE,
       PINYIN,
       '' AS AGENCYATTRIB,
       '' AS ISBENJIDANWEI,
       '' AS AGENCY_ABBREVIATION,
       '' AS AGENCY_LEADER_PER_NAME,
       '' AS AGENCY_ADD,
       '' AS LOCATION,
       '' AS CAPITAL_TYPE,
       '' AS EXECUTIVE_ACC,
       '' AS IS_PRE_DEPAR_FIN_ACCOUNTS,
       '' AS IS_PRE_FIN_REP_GOV_DEP,
       '' AS IS_PRE_STA_OWN_ASSE_REP_ADM,
       '' AS IS_VIRTUAL_UNIT,
       '' AS AGENCY_LEVEL_CODE,
       '' AS ADMIN_STAF_NUM,
       '' AS INST_STAF_NUM,
       '' AS WORKER_STAF_NUM,
       '' AS ACTU_STAF_NUM,
       '' AS ACTUNOW_STAF_NUM,
       '' AS DR_NUM,
       '' AS MASTER_NUM,
       '' AS UNDERGR_NUM,
       '' AS ACADEMY_NUM,
       '' AS ORDINARY_HIGH_SCH_STUD_NUM,
       '' AS JUNIOR_HIGH_SCH_STUD_NUM,
       '' AS PRIARY_SCH_STUD_NUM,
       '' AS KINDERGARTEN_CHILDREN_NUM,
       '' AS OTHER_STUD_NUM,
       FUNDSUP,
       ALIAS,
       FISCAL_YEAR AS YEAR,
       DBVERSION,
       CANCELTIME,
       PAYTYPEFLAG,
       SALARYTYPEFLAG,
       SPEACCTTYPEFLAG,
       GLTYPEFLAG,
       BGTTYPEFLAG,
       ISTOWN,
       TOWNCODE,
       DWSXBS,
       FPCOL1,
       FPCOL2,
       FPCOL3,
       FPCOL4,
       FPCOL5,
       AAORDERNO,
       ISCZAGENCY,
       LEADERNAME,
       UNIFSOC_CRED_CODE AS UNIFSOCCREDCODE,
       FININTORG,
       IND AS IND_CODE,
       SUPDEP,
       AGENCY_ADM_LEVEL_CODE,
       AGENCYTYPE,
       AGENCYLEVEL,
       TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24:MM:SS'),
               'YYYY/MM/DD HH24:MI:SS') AS START_DATE,
       '' AS END_DATE,
       TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24:MM:SS'),
               'YYYY/MM/DD HH24:MI:SS') AS UPDATE_TIME,
       TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24:MM:SS'),
               'YYYY/MM/DD HH24:MI:SS') AS CREATE_TIME,
       TO_CHAR(IS_ENABLED) AS STATUS,
       CASE
         WHEN IS_DELETED = 1 THEN
          2
         WHEN IS_DELETED = 2 THEN
          2
         WHEN IS_DELETED = 3 THEN
          1
       END IS_DELETED,
       1 AS IS_STANDARD
  FROM ELE_VD00010 T
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';


V_SQL_VD09001:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD09001 AS
SELECT T.ELE_CODE PRO_CAT_CODE,
       T.ELE_CODE AS GUID,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.ELE_CATALOG_ID,
       T.MOF_DIV_CODE PROVINCE,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED,
       T.UPDATE_TIME,
       T.IS_DELETED STATUS,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.FISCAL_YEAR YEAR,
       T.PRO_JTYPE PROJTYPE
  FROM ELE_VD09001 T, ELE_VD09001 T1
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';
V_SQL_VD10003:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD10003 AS
SELECT T.ELE_CODE AS GUID,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.ELE_CATALOG_ID,
       T.MOF_DIV_CODE AS PROVINCE,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED,
       T.UPDATE_TIME,
       T.IS_DELETED,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.FISCAL_YEAR AS YEAR,
       T.FUND_TYPE_CODE
  FROM ELE_VD10003 T, ELE_VD10003 T1
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';
V_SQL_VD10004:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD10004 AS
SELECT T.FUNCTYPE,
       T.ELE_CODE AS GUID,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.ELE_CATALOG_ID,
       T.MOF_DIV_CODE AS PROVINCE,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.LEVEL_NO AS LEVELNO,
       CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED STATUS,
       T.UPDATE_TIME,
       T.IS_DELETED,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.FISCAL_YEAR,
       T.FISCAL_YEAR AS YEAR,
       T.FUND_TYPE_CODE
  FROM ELE_VD10004 T, ELE_VD10004 T1
 WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';

V_SQL_VC01004:=Q'[
CREATE OR REPLACE VIEW V_ELE_VC01004 AS
SELECT T.ADMDIV,
       T.ELE_CATALOG_ID,
       T.ELE_CATALOG_CODE,
       T.ELE_CODE AS GUID,
       T.FISCAL_YEAR AS YEAR,
       T.MOF_DIV_CODE AS PROVINCE,
       T.LEVEL_NO AS LEVELNO,
       T.IS_LEAF AS ISLEAF,
       T.START_DATE,
       T.END_DATE,
       T.IS_ENABLED AS STATUS,
       T.UPDATE_TIME,
       T.ELE_CODE AS CODE,
       T.ELE_NAME AS NAME,
       T.IS_DELETED,
       DECODE(T.PARENT_ID, '0', '0', T1.ELE_CODE) AS SUPERGUID,
       T.IS_STANDARD,
       T.CREATE_TIME,
       T.REMARK
  FROM ELE_VC01004 T, ELE_VC01004 T1
 WHERE T.IS_ENABLED =1 
   AND T.IS_DELETED =2
   AND T.PARENT_ID = T1.ELE_ID(+)
   AND T.MOF_DIV_CODE = T1.MOF_DIV_CODE(+)
   AND T.FISCAL_YEAR = T1.FISCAL_YEAR(+)
   AND T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';


V_SQL_VD08001:=Q'[
CREATE OR REPLACE VIEW V_ELE_VD08001 AS
SELECT T.ELE_CODE AS GUID,
       ELE_CODE AS CODE,
       ELE_NAME AS NAME,
       'B0722B53403B7740E0533203A8C0DF7E' AS ELE_CATALOG_ID,
       'VD08001' AS ELE_CATALOG_CODE,
       IS_LEAF AS ISLEAF,
       LEVEL_NO AS LEVELNO,
       REMARK,
       CREATE_TIME,
       VERSION,
       PARENT_ID AS SUPERGUID,
       NVL((SELECT ELE_CODE
          FROM ELE_VD08001 F
         WHERE F.FISCAL_YEAR = T.FISCAL_YEAR
           AND F.MOF_DIV_CODE = T.MOF_DIV_CODE
           AND F.ELE_ID = T.PARENT_ID),'0') AS PARENT_ID,
       PARENT_ADM_DIV_CODE,
       MOF_DIV_TYPE,
       ADM_DIV_CODE,
       IS_ADMDIV,
       IS_DELETED,
       IS_STANDARD,
       UPDATE_TIME,
       IS_ENABLED,
       SRCGUID,
       DESGUID,
       START_DATE,
       PINYIN,
       EMW,
       ALIAS,
       FGDG,
       END_DATE,
       STATUS,
       FISCAL_YEAR AS YEAR,
       MOF_DIV_CODE AS PROVINCE,
       ADMDIVGBCODE,
       DIRUNDERFLAG,
       ECONBELT,
       ECONBELTGUID,
       FINADMLEVEL,
       FINADMLEVELMARK,
       FOODREGFLAG,
       GAPDIVFLAG,
       HARDDISFLAG,
       MINORITYDISFLAG,
       OBAORFLAG,
       PLANCITYFLAG,
       POVDEVDISFLAG,
       REVDISFLAG,
       DBVERSION,
       CANCELTIME,
       ISSTRAIGHTCOUNTY
  FROM ELE_VD08001 T
 WHERE T.IS_ENABLED =1 
   AND T.IS_DELETED =2 
   AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
]';

EXECUTE IMMEDIATE V_SQL_VD00010;
EXECUTE IMMEDIATE V_SQL_VD09001;
EXECUTE IMMEDIATE V_SQL_VD10003;
EXECUTE IMMEDIATE V_SQL_VD10004;
EXECUTE IMMEDIATE V_SQL_VC01004;
EXECUTE IMMEDIATE V_SQL_VD08001;
END;










