DECLARE
  J INTEGER;
  I INTEGER;
  H INTEGER;
  CURSOR T_TABLES IS
    SELECT * FROM ELE_CATALOG T  WHERE T.CATALOG_TYPE='1' AND ELE_CATALOG_CODE NOT IN (
    'VD10004','VD10003','VC01004','VD00010','VD08002','VD08001','VD09001'
    );
BEGIN
  FOR T_ROW IN T_TABLES LOOP
   SELECT COUNT(*) INTO J FROM USER_TABLES T WHERE T.TABLE_NAME = T_ROW.ELE_SOURCE;
    IF J >0 THEN 
      EXECUTE IMMEDIATE '
      CREATE OR REPLACE VIEW "V_'||CASE 
         WHEN T_ROW.ELE_SOURCE <> 'ELE_UNION' THEN T_ROW.ELE_SOURCE 
         WHEN T_ROW.ELE_SOURCE = 'ELE_UNION' THEN T_ROW.ELE_SOURCE||'_'||T_ROW.ELE_CATALOG_CODE
         END||'"
          AS
    SELECT (SELECT ELE_ID FROM ELE_VD08001 A WHERE  A.ELE_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'')
    AND A.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''YEAR'')) AS ADMDIV ,
         T.ELE_CATALOG_ID,
         T.ELE_CATALOG_CODE,
         T.ELE_CODE AS GUID,
         T.FISCAL_YEAR AS YEAR,
         GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'') AS PROVINCE,
         T.LEVEL_NO AS LEVELNO,
         CASE WHEN T.IS_LEAF = 1 THEN 1 WHEN T.IS_LEAF = 2 THEN 0 WHEN T.IS_LEAF = 0 THEN 0 END ISLEAF,
         T.START_DATE,
         T.END_DATE,
         CASE WHEN T.IS_ENABLED = 1 THEN ''1'' WHEN T.IS_ENABLED = 2 AND T.IS_DELETED= 2 THEN ''2''  WHEN  T.IS_ENABLED = 2 AND T.IS_DELETED= 1 THEN ''3''
            END STATUS,
         T.UPDATE_TIME,
         T.ELE_CODE AS CODE,
         T.ELE_NAME AS NAME,
         T.IS_DELETED,
         (SELECT ELE_CODE FROM '||T_ROW.ELE_SOURCE||' T1 WHERE  T.PARENT_ID = T1.ELE_ID AND  T1.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'')
     AND T1.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''YEAR'')) AS SUPERGUID,
         T.IS_STANDARD,
         '''' AS  PINYIN,
         T.CREATE_TIME
    FROM '||T_ROW.ELE_SOURCE||' T
   WHERE T.IS_ENABLED =1 AND T.IS_DELETED =2 AND
   '||CASE 
      WHEN T_ROW.ELE_SOURCE = 'ELE_UNION' THEN 'T.ELE_CATALOG_CODE = '''||T_ROW.ELE_CATALOG_CODE||''' AND'
        END||'
     T.MOF_DIV_CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'')
     AND T.FISCAL_YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''YEAR'')
      ';
    END IF;
  END LOOP;
END;
