--FASP_T_DICDS增加条件过滤
declare
FASP_T_DICDS VARCHAR2(4000);
BEGIN
FASP_T_DICDS:=q'[
CREATE OR REPLACE VIEW FASP_T_DICDS AS
SELECT
    ELE_CATALOG_ID AS GUID,
    ELE_CATALOG_CODE AS CODE,
    ELE_CATALOG_NAME AS NAME,
    ELEMENTCODE AS ELEMENTCODE,
    '' ALIAS,
    APPLY AS APPLY,
    CODEMODE AS CODEMODE,
    '' PUBLISHNAME,
    REMARK AS REMARK,
    '1' STATUS,
    CREATE_TIME AS CREATETIME,
    START_DATE AS STARTTIME,
    END_DATE AS ENDTIME,
    MOF_DIV_CODE AS PROVINCE,
    T.FISCAL_YEAR AS YEAR,
    0 VERSION,
    TYPEGUID AS TYPEGUID,
    CASE
WHEN UPPER(ELE_SOURCE) = 'ELE_UNION' THEN
'V_' || ELE_SOURCE ||'_'|| ELE_CATALOG_CODE
ELSE
'V_' || ELE_SOURCE
END AS TABLECODE,
    '' CRC,
    '' ISEXPORTTRANSLATE,
    '' EXPORTRANSLATEGUIDFORMAT,
    '' ISACROSSFISCAL,
    '' ACROSSFISCALFORMAT,
    '' CACHETYPE,
    '' ISPUBLIC,
    '' TRANSACTIONCACHE,
    CODEMODE AS CODETYEP,
    --DBVERSION,
    '' IMPORTSTANDARD,
    '' ISNORMVERSION
FROM ELE_CATALOG T 
WHERE T.IS_ENABLED ='1' 
AND T.IS_DELETED= '2'
]';
execute immediate FASP_T_DICDS;
end;










