--中台库执行
DECLARE
  I INTEGER;
  J INTEGER;
  H INTEGER;
  K INTEGER;
  A INTEGER;
BEGIN
   SELECT COUNT(1) INTO I FROM USER_TABLES WHERE TABLE_NAME='FW_T_APP';  
   IF I<=0 THEN
     EXECUTE IMMEDIATE '
     CREATE TABLE FW_T_APP
      (
        APP_CODE VARCHAR2(50) NOT NULL,
        APP_NAME VARCHAR2(50) NOT NULL,
        APP_IDEN VARCHAR2(50) NOT NULL
      )
     ';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE FW_T_APP IS ''系统表''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_APP.APP_CODE IS ''编码''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_APP.APP_NAME IS ''名称''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_APP.APP_IDEN IS ''标识''';
    EXECUTE IMMEDIATE 'INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''001'', ''编制'', ''bz'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''002'', ''执行'', ''zx'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''003'', ''非税'', ''fs'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''004'', ''资产'', ''zc'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''005'', ''核算'', ''hs'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''006'', ''财报'', ''cb'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''007'', ''决算'', ''js'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''008'', ''基础'', ''bas'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''009'', ''预算'', ''bgt'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''010'', ''项目'', ''pdm'')';
    EXECUTE IMMEDIATE '
    INSERT INTO FW_T_APP (APP_CODE, APP_NAME, APP_IDEN)
    VALUES (''011'', ''绩效'', ''pmkpi'')';
    COMMIT;
   END IF;
   SELECT COUNT(1) INTO J FROM USER_TABLES WHERE TABLE_NAME='FASP_EXT_ATTRIBUTE';  
   IF J<=0 THEN
     EXECUTE IMMEDIATE '
     CREATE TABLE FASP_EXT_ATTRIBUTE
      (
        EXT_CODE  VARCHAR2(50) NOT NULL,
        EXT_NAME  VARCHAR2(50) NOT NULL,
        EXT_IDEN  VARCHAR2(50) NOT NULL,
        EXT_TABLE VARCHAR2(50) NOT NULL
      )
     ';
     EXECUTE IMMEDIATE 'COMMENT ON TABLE FASP_EXT_ATTRIBUTE IS ''属性表''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_ATTRIBUTE.EXT_CODE IS ''编码''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_ATTRIBUTE.EXT_NAME IS ''名称''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_ATTRIBUTE.EXT_IDEN IS ''标识''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_ATTRIBUTE.EXT_TABLE IS ''表名''';
     EXECUTE IMMEDIATE 'insert into fasp_ext_attribute (EXT_CODE, EXT_NAME, EXT_IDEN, EXT_TABLE)
     values (''01'', ''系统标识'', ''appid'', ''fw_t_app'')';
     EXECUTE IMMEDIATE 'insert into fasp_ext_attribute (EXT_CODE, EXT_NAME, EXT_IDEN, EXT_TABLE)
     values (''02'', ''乡镇标识'', ''countryid'', ''fw_t_country'')';
     COMMIT;
   END IF;
   SELECT COUNT(1) INTO H FROM USER_TABLES WHERE TABLE_NAME='FASP_EXT_MAPPING';  
   IF H<=0 THEN
     EXECUTE IMMEDIATE '
     CREATE TABLE FASP_EXT_MAPPING
      (
        EXT_CODE     VARCHAR2(50) NOT NULL,
        ELE_CODE     VARCHAR2(50) NOT NULL,
        ATTR_CODE    VARCHAR2(50) NOT NULL,
        MOF_DIV_CODE VARCHAR2(9) NOT NULL,
        FISCAL_YEAR  VARCHAR2(4) NOT NULL
      )
     ';
     EXECUTE IMMEDIATE 'COMMENT ON TABLE FASP_EXT_MAPPING IS ''映射表''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_MAPPING.EXT_CODE IS ''属性编码''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_MAPPING.ELE_CODE IS ''单位要素编码''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_MAPPING.ATTR_CODE IS ''系统属性编码''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_MAPPING.MOF_DIV_CODE IS ''区划''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FASP_EXT_MAPPING.FISCAL_YEAR IS ''年度''';

   END IF;  
   SELECT COUNT(1) INTO K FROM USER_TABLES WHERE TABLE_NAME='FW_T_COUNTRY';  
   IF K<=0 THEN
     EXECUTE IMMEDIATE '
     CREATE TABLE FW_T_COUNTRY
      (
        APP_CODE VARCHAR2(50) NOT NULL,
        APP_NAME VARCHAR2(50) NOT NULL,
        APP_IDEN VARCHAR2(50) NOT NULL
      )
     ';
     EXECUTE IMMEDIATE 'COMMENT ON TABLE FW_T_COUNTRY IS ''系统表''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_COUNTRY.APP_CODE IS ''编码''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_COUNTRY.APP_NAME IS ''名称''';
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN FW_T_COUNTRY.APP_IDEN IS ''标识''';  

     EXECUTE IMMEDIATE 'INSERT INTO FW_T_COUNTRY (APP_CODE, APP_NAME, APP_IDEN)
     VALUES (''1'', ''是'', ''true'')';  
     EXECUTE IMMEDIATE 'INSERT INTO FW_T_COUNTRY (APP_CODE, APP_NAME, APP_IDEN)
     VALUES (''2'', ''否'', ''false'')';  
   COMMIT; 
   END IF;
END;
