DECLARE
V_SQL VARCHAR2(4000);
BEGIN
  --DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE NOT IN(SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT IN('ELE_DICCOLUMN','ELE_DICTABLE','ELE_UNION','ELE_CATALOG') AND TABLE_NAME LIKE 'ELE_%');
  DELETE FROM FASP_SYNC_TABLE;
  FOR T IN(SELECT TABLE_NAME TABLECODE FROM USER_TABLES WHERE TABLE_NAME NOT IN('ELE_DICCOLUMN','ELE_DICTABLE') AND TABLE_NAME LIKE 'ELE_%'  AND EXISTS(SELECT 1 FROM ELE_CATALOG WHERE ELE_SOURCE=TABLE_NAME)) LOOP
  BEGIN
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT MOF_DIV_CODE,0,1,1,'''||T.TABLECODE||''' FROM '||T.TABLECODE;
  V_SQL:='CREATE OR REPLACE TRIGGER TRI_'||SUBSTR(T.TABLECODE,0,21)||'_EASY ';
  V_SQL:=V_SQL||' AFTER INSERT OR UPDATE OR DELETE ON '||T.TABLECODE;
  V_SQL:=V_SQL||' FOR EACH ROW ';
  V_SQL:=V_SQL||' DECLARE ';
  V_SQL:=V_SQL||' V_PROVINCE VARCHAR(32);';
  V_SQL:=V_SQL||' BEGIN';
  V_SQL:=V_SQL||' IF INSERTING OR UPDATING THEN V_PROVINCE:=:NEW.MOF_DIV_CODE;ELSE V_PROVINCE:=:OLD.MOF_DIV_CODE;END IF;';
  V_SQL:=V_SQL||' DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE='''||T.TABLECODE||''' AND PROVINCE=V_PROVINCE;';
  V_SQL:=V_SQL||' INSERT INTO FASP_SYNC_TABLE(TABLECODE, PROVINCE, SRCVERSION, DESVERSION, ADDCATALOG) ';
  V_SQL:=V_SQL||' SELECT '''||T.TABLECODE||''',V_PROVINCE, 0, 1, 1 FROM DUAL;END;';
  EXECUTE IMMEDIATE V_SQL;
  EXCEPTION
    WHEN OTHERS THEN
      --NULL;
      DBMS_OUTPUT.PUT_LINE('TABLENAME='||T.TABLECODE);
      --DBMS_OUTPUT.PUT_LINE('TABLENAME='||T.TABLECODE||'SQLCODE='||SQLCODE||'SQLERRMSG='||SQLERRM);
  END;
  END LOOP;
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT PROVINCE,0,1,1,''ELE_DICTABLE'' FROM ELE_DICTABLE';
  V_SQL:='CREATE OR REPLACE TRIGGER TRI_ELE_DICTABLE_EASY ';
  V_SQL:=V_SQL||' AFTER INSERT OR UPDATE OR DELETE ON ELE_DICTABLE';
  V_SQL:=V_SQL||' FOR EACH ROW ';
  V_SQL:=V_SQL||' DECLARE ';
  V_SQL:=V_SQL||' V_PROVINCE VARCHAR(32);';
  V_SQL:=V_SQL||' BEGIN';
  V_SQL:=V_SQL||' IF INSERTING OR UPDATING THEN V_PROVINCE:=:NEW.PROVINCE;ELSE V_PROVINCE:=:OLD.PROVINCE;END IF;';
  V_SQL:=V_SQL||' DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''ELE_DICTABLE'' AND PROVINCE=V_PROVINCE;';
  V_SQL:=V_SQL||' INSERT INTO FASP_SYNC_TABLE(TABLECODE, PROVINCE, SRCVERSION, DESVERSION, ADDCATALOG) ';
  V_SQL:=V_SQL||' SELECT ''ELE_DICTABLE'',V_PROVINCE, 0, 1, 1 FROM DUAL;END;';
  EXECUTE IMMEDIATE V_SQL;
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT PROVINCE,0,1,1,''ELE_DICCOLUMN'' FROM ELE_DICCOLUMN';
  V_SQL:='CREATE OR REPLACE TRIGGER TRI_ELE_DICCOLUMN_EASY ';
  V_SQL:=V_SQL||' AFTER INSERT OR UPDATE OR DELETE ON ELE_DICCOLUMN';
  V_SQL:=V_SQL||' FOR EACH ROW ';
  V_SQL:=V_SQL||' DECLARE ';
  V_SQL:=V_SQL||' V_PROVINCE VARCHAR(32);';
  V_SQL:=V_SQL||' BEGIN';
  V_SQL:=V_SQL||' IF INSERTING OR UPDATING THEN V_PROVINCE:=:NEW.PROVINCE;ELSE V_PROVINCE:=:OLD.PROVINCE;END IF;';
  V_SQL:=V_SQL||' DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''ELE_DICCOLUMN'' AND PROVINCE=V_PROVINCE;';
  V_SQL:=V_SQL||' INSERT INTO FASP_SYNC_TABLE(TABLECODE, PROVINCE, SRCVERSION, DESVERSION, ADDCATALOG) ';
  V_SQL:=V_SQL||' SELECT ''ELE_DICCOLUMN'',V_PROVINCE, 0, 1, 1 FROM DUAL;END;';
  EXECUTE IMMEDIATE V_SQL;
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT MOF_DIV_CODE,0,1,1,''ELE_ELEMENT'' FROM ELE_ELEMENT';
  V_SQL:='CREATE OR REPLACE TRIGGER TRI_ELE_ELEMENT_EASY ';
  V_SQL:=V_SQL||' AFTER INSERT OR UPDATE OR DELETE ON ELE_ELEMENT';
  V_SQL:=V_SQL||' FOR EACH ROW ';
  V_SQL:=V_SQL||' DECLARE ';
  V_SQL:=V_SQL||' V_PROVINCE VARCHAR(32);';
  V_SQL:=V_SQL||' BEGIN';
  V_SQL:=V_SQL||' IF INSERTING OR UPDATING THEN V_PROVINCE:=:NEW.MOF_DIV_CODE;ELSE V_PROVINCE:=:OLD.MOF_DIV_CODE;END IF;';
  V_SQL:=V_SQL||' DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''ELE_ELEMENT'' AND PROVINCE=V_PROVINCE;';
  V_SQL:=V_SQL||' INSERT INTO FASP_SYNC_TABLE(TABLECODE, PROVINCE, SRCVERSION, DESVERSION, ADDCATALOG) ';
  V_SQL:=V_SQL||' SELECT ''ELE_ELEMENT'',V_PROVINCE, 0, 1, 1 FROM DUAL;END;';
  EXECUTE IMMEDIATE V_SQL;
  EXECUTE IMMEDIATE 'DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''FASP_T_CAUSER''';
  EXECUTE IMMEDIATE 'DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''FASP_T_CAROLE''';
  EXECUTE IMMEDIATE 'DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''FASP_T_CAUSERROLE''';
  EXECUTE IMMEDIATE 'DELETE FROM FASP_SYNC_TABLE WHERE TABLECODE=''FASP_T_CAROLEMENU''';
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT PROVINCE,0,1,1,''FASP_T_CAUSER'' FROM FASP_T_CAUSER';
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT NVL(PROVINCE,-1),0,1,1,''FASP_T_CAROLE'' FROM FASP_T_CAROLE';
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT PROVINCE,0,1,1,''FASP_T_CAUSERROLE'' FROM FASP_T_CAUSERROLE';
  EXECUTE IMMEDIATE 'INSERT INTO FASP_SYNC_TABLE(PROVINCE,SRCVERSION,DESVERSION,ADDCATALOG,TABLECODE) SELECT DISTINCT PROVINCE,0,1,1,''FASP_T_CAROLEMENU'' FROM FASP_T_CAROLEMENU';
  COMMIT;
END;
/
