SELECT GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_SETPARM('', '320000000', '2022', '') FROM DUAL; 
--权限配置
SELECT * FROM FASP_T_DATARIGHT WHERE NAME='摸乐1号';
--权限分配
SELECT * FROM FASP_T_DATARIGHTRP WHERE DATARIGHTID=(SELECT GUID FROM FASP_T_DATARIGHT WHERE NAME='摸乐1号');
--权限配置规则
SELECT * FROM FASP_T_BUSRURULE WHERE GUID=(SELECT RULEID FROM FASP_T_DATARIGHT WHERE NAME='摸乐1号');
--权限配置规则子表
SELECT * FROM FASP_T_BUSRURULESUB WHERE RULEGUID=(SELECT RULEID FROM FASP_T_DATARIGHT WHERE NAME='摸乐1号');
--权限配置规则扩展表
SELECT * FROM FASP_T_BUSRURULEEX WHERE RULESUBGUID =(SELECT GUID FROM FASP_T_BUSRURULESUB WHERE RULEGUID=(SELECT RULEID FROM FASP_T_DATARIGHT WHERE NAME='摸乐1号'));



P#FASP_T_BUSRUMPRULE,级联控制规则主表
P#FASP_T_BUSRUMPRULESUB,输入对照规则子表
P#FASP_T_BUSRUMPRULELINK,输入对照规则明细表

/


--权限配置规则
P#FASP_T_BUSRURULE        GUID        规则主键
P#FASP_T_BUSRURULE        NAME        名称
P#FASP_T_BUSRURULE        WHERESQL        拼接sql
P#FASP_T_BUSRURULE        STATUS        状态
P#FASP_T_BUSRURULE        DBVERSION        版本
P#FASP_T_BUSRURULE        ADMDIV        区划
P#FASP_T_BUSRURULE        PROVINCE        区划
P#FASP_T_BUSRURULE        YEAR        年度

--权限配置规则子表
P#FASP_T_BUSRURULESUB        GUID        规则子表主键
P#FASP_T_BUSRURULESUB        RULEGUID        规则主键P#FASP_T_BUSRURULE的追歼
P#FASP_T_BUSRURULESUB        ORDERNUM        排序
P#FASP_T_BUSRURULESUB        FRONTBRACKET        前括号
P#FASP_T_BUSRURULESUB        RULEELEMENT        来源项项ELEMENT_CODE
P#FASP_T_BUSRURULESUB        LOGICTYPE        逻辑类型and or
P#FASP_T_BUSRURULESUB        TEXTVALUE        文本值
P#FASP_T_BUSRURULESUB        BACKBRACKET        后括号
P#FASP_T_BUSRURULESUB        LOGICSYMBOL        逻辑标志
P#FASP_T_BUSRURULESUB        ACCORD        规则依据1，0
P#FASP_T_BUSRURULESUB        STATUS        状态
P#FASP_T_BUSRURULESUB        DBVERSION        版本
P#FASP_T_BUSRURULESUB        ADMDIV        区划
P#FASP_T_BUSRURULESUB        PROVINCE        区划
P#FASP_T_BUSRURULESUB        YEAR        年度
P#FASP_T_BUSRURULESUB        CSID        来源GUID fasp_t_dicds等
P#FASP_T_BUSRURULESUB        BATCHGUID        批量主键


--权限配置
P#FASP_T_DATARIGHT        GUID        主键
P#FASP_T_DATARIGHT        NAME        名称
P#FASP_T_DATARIGHT        RULEID        规则主键
P#FASP_T_DATARIGHT        DBVERSION        版本
P#FASP_T_DATARIGHT        CREATER        创建人
P#FASP_T_DATARIGHT        CREATETIME        创建时间
P#FASP_T_DATARIGHT        APPID        系统标志
P#FASP_T_DATARIGHT        PROVINCE        区划
P#FASP_T_DATARIGHT        YEAR        年度
P#FASP_T_DATARIGHT        STATUS        状态

--权限分配
P#FASP_T_DATARIGHTRP        GUID        主键
P#FASP_T_DATARIGHTRP        ROLEID        分配角色主键
P#FASP_T_DATARIGHTRP        MENUID        菜单主键
P#FASP_T_DATARIGHTRP        DATARIGHTID        权限分配主键FASP_T_DATARIGHT的主键
P#FASP_T_DATARIGHTRP        ISFROM        是否来源:1 为有来源，其他为去向
P#FASP_T_DATARIGHTRP        ISTO        ISTO : 是否去向
P#FASP_T_DATARIGHTRP        PROVINCE        区划
P#FASP_T_DATARIGHTRP        YEAR        年度
P#FASP_T_DATARIGHTRP        USERGUID        用户主键FASP_T_CAUSER的主键






--权限配置规则扩展表
P#FASP_T_BUSRURULEEX        GUID        规则扩展主键
P#FASP_T_BUSRURULEEX        RULESUBGUID        规则子表主键P#FASP_T_BUSRURULESUB
P#FASP_T_BUSRURULEEX        ORDERNUM        排序
P#FASP_T_BUSRURULEEX        FRONTBRACKET        前括号
P#FASP_T_BUSRURULEEX        RULEELEMENT        elementcode
P#FASP_T_BUSRURULEEX        LOGICTYPE        逻辑类型
P#FASP_T_BUSRURULEEX        TEXTVALUE        文本值
P#FASP_T_BUSRURULEEX        BACKBRACKET        后括号
P#FASP_T_BUSRURULEEX        LOGICSYMBOL        逻辑符
P#FASP_T_BUSRURULEEX        ACCORD        规则依据
P#FASP_T_BUSRURULEEX        STATUS        状态
P#FASP_T_BUSRURULEEX        DBVERSION        版本
P#FASP_T_BUSRURULEEX        ADMDIV        区划
P#FASP_T_BUSRURULEEX        PROVINCE        区划
P#FASP_T_BUSRURULEEX        YEAR        年度
P#FASP_T_BUSRURULEEX        CSID        fasp_t_dicds主键
P#FASP_T_BUSRURULEEX        BATCHGUID        批量id




SELECT GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_SETPARM('', '320000000', '2022', '') FROM DUAL; 
--权限配置
SELECT * FROM FASP_T_DATARIGHT ;
--权限分配
SELECT * FROM FASP_T_DATARIGHTRP;
--权限配置规则
SELECT * FROM FASP_T_BUSRURULE;
--权限配置规则子表
SELECT * FROM FASP_T_BUSRURULESUB;
--权限配置规则扩展表
SELECT * FROM FASP_T_BUSRURULEEX ;
--级联控制规则主表
SELECT t.*,t.rowid FROM FASP_T_BUSRUMPRULE  t  ;
--输入对照规则子表
SELECT t.*,t.rowid FROM FASP_T_BUSRUMPRULE  t  ;
--输入对照规则明细表
SELECT t.*,t.rowid FROM FASP_T_BUSRUMPRULE  t  ;
