
(SELECT trim(regexp_substr('PRO_ID,SETUP_YEAR,PRO_CODE,PRO_NAME,AGENCY_CODE,TRAOBJ_AGENCY_CODE,CEN_TRA_PRO_CODE,PRO_SOURCE_CODE,PRO_TERM,PRO_START_YEAR,FUN_RES_CODE,PRO_CAT_CODE,DISTRI_TYPE_CODE,IS_TRACK,IS_CAPTIAL_CONS_PRO,PRO_TOTAL_AMT,SCOI_INVEST_FUND,MOF_DEP_CODE,PRO_DEPREVIEW,PRO_BGTREVIEW,DEP_AUD_OPINION_CODE,MOF_AUD_OPINION_CODE,PRO_DESC,DRAFT_TEMPLATE_CODE,IS_END,IS_SCIENTIFIC,IS_DELETED,IS_USESET,CREATE_TIME,UPDATE_TIME,START_DATE,END_DATE,MOF_DIV_CODE,FISCAL_YEAR,STATUS,ISNORMVERSION,PRJNECESSITY,C3,YBGGYS,ZFXJJ,GYZBJ,SBJJ,SNJZZJ,ZTZJ,ISAPPROVAL,PRJMANAGERNAME,PRJCONTACTPHONE,PRJBASETYPECODE,PRJBASETYPENAME,PRO_END_YEAR,PRJCONTENT,PRJALLTARGET','[^,]+',1,LEVEL)) column_name 
FROM dual CONNECT BY LEVEL <= regexp_count('PRO_ID,SETUP_YEAR,PRO_CODE,PRO_NAME,AGENCY_CODE,TRAOBJ_AGENCY_CODE,CEN_TRA_PRO_CODE,PRO_SOURCE_CODE,PRO_TERM,PRO_START_YEAR,FUN_RES_CODE,PRO_CAT_CODE,DISTRI_TYPE_CODE,IS_TRACK,IS_CAPTIAL_CONS_PRO,PRO_TOTAL_AMT,SCOI_INVEST_FUND,MOF_DEP_CODE,PRO_DEPREVIEW,PRO_BGTREVIEW,DEP_AUD_OPINION_CODE,MOF_AUD_OPINION_CODE,PRO_DESC,DRAFT_TEMPLATE_CODE,IS_END,IS_SCIENTIFIC,IS_DELETED,IS_USESET,CREATE_TIME,UPDATE_TIME,START_DATE,END_DATE,MOF_DIV_CODE,FISCAL_YEAR,STATUS,ISNORMVERSION,PRJNECESSITY,C3,YBGGYS,ZFXJJ,GYZBJ,SBJJ,SNJZZJ,ZTZJ,ISAPPROVAL,PRJMANAGERNAME,PRJCONTACTPHONE,PRJBASETYPECODE,PRJBASETYPENAME,PRO_END_YEAR,PRJCONTENT,PRJALLTARGET',',')+1)
minus
select column_name from user_tab_columns where table_name = 'PM_PROJECT_INFO';



--1.刷新所有码表parent_id 为0
declare
   cursor t_columns is select * from user_tab_columns t where t.table_name='PM_PROJECT_INFO' and t.COLUMN_NAME in (
''
    );
BEGIN
   for t_row in t_columns loop
       dbms_output.put_line('alter table PM_PROJECT_INFO '|| t_row.column_name || ' add ' || t_row.data_type || '(' || t_row.data_length ||');');
   end loop;
END;








