(select column_name
          from user_tab_columns
         where table_name = 'ELE_UNION'
        minus
        select column_name
          from user_tab_columns
         where table_name = 'ELE_VD09001')
union 
(select column_name
         from user_tab_columns
        where table_name = 'ELE_VD09001'
       minus
       select column_name
         from user_tab_columns
        where table_name = 'ELE_UNION');
/* 2.比较表数据 */
(select *
          from t_A
        minus
        select * from t_B)
union 
(select *
         from t_B
       minus
       select * from t_A)
;









(SELECT trim(regexp_substr('PRO_ID,SETUP_YEAR,PRO_CODE,PRO_NAME,AGENCY_CODE,TRAOBJ_AGENCY_CODE,CEN_TRA_PRO_CODE,PRO_SOURCE_CODE,PRO_TERM,PRO_START_YEAR,FUN_RES_CODE,PRO_CAT_CODE,DISTRI_TYPE_CODE,IS_TRACK,IS_CAPTIAL_CONS_PRO,PRO_TOTAL_AMT,SCOI_INVEST_FUND,MOF_DEP_CODE,PRO_DEPREVIEW,PRO_BGTREVIEW,DEP_AUD_OPINION_CODE,MOF_AUD_OPINION_CODE,PRO_DESC,DRAFT_TEMPLATE_CODE,IS_END,IS_SCIENTIFIC,IS_DELETED,IS_USESET,CREATE_TIME,UPDATE_TIME,START_DATE,END_DATE,MOF_DIV_CODE,FISCAL_YEAR,STATUS,ISNORMVERSION,PRJNECESSITY,C3,YBGGYS,ZFXJJ,GYZBJ,SBJJ,SNJZZJ,ZTZJ,ISAPPROVAL,PRJMANAGERNAME,PRJCONTACTPHONE,PRJBASETYPECODE,PRJBASETYPENAME,PRO_END_YEAR,PRJCONTENT,PRJALLTARGET','[^,]+',1,LEVEL)) column_name 
FROM dual CONNECT BY LEVEL <= regexp_count('PRO_ID,SETUP_YEAR,PRO_CODE,PRO_NAME,AGENCY_CODE,TRAOBJ_AGENCY_CODE,CEN_TRA_PRO_CODE,PRO_SOURCE_CODE,PRO_TERM,PRO_START_YEAR,FUN_RES_CODE,PRO_CAT_CODE,DISTRI_TYPE_CODE,IS_TRACK,IS_CAPTIAL_CONS_PRO,PRO_TOTAL_AMT,SCOI_INVEST_FUND,MOF_DEP_CODE,PRO_DEPREVIEW,PRO_BGTREVIEW,DEP_AUD_OPINION_CODE,MOF_AUD_OPINION_CODE,PRO_DESC,DRAFT_TEMPLATE_CODE,IS_END,IS_SCIENTIFIC,IS_DELETED,IS_USESET,CREATE_TIME,UPDATE_TIME,START_DATE,END_DATE,MOF_DIV_CODE,FISCAL_YEAR,STATUS,ISNORMVERSION,PRJNECESSITY,C3,YBGGYS,ZFXJJ,GYZBJ,SBJJ,SNJZZJ,ZTZJ,ISAPPROVAL,PRJMANAGERNAME,PRJCONTACTPHONE,PRJBASETYPECODE,PRJBASETYPENAME,PRO_END_YEAR,PRJCONTENT,PRJALLTARGET',',')+1)
minus
select column_name from user_tab_columns where table_name = 'PM_PROJECT_INFO'
       
