CREATE OR REPLACE TRIGGER TR_FASP_T_PUBMENU_SYNC
  AFTER INSERT OR UPDATE OR DELETE ON FASP_T_PUBMENU
  FOR EACH ROW
DECLARE
  V_PROVINCE VARCHAR(32);
BEGIN
  IF INSERTING OR UPDATING THEN
    V_PROVINCE := :NEW.PROVINCE;
  ELSE
    V_PROVINCE := :OLD.PROVINCE;
  END IF;
  DELETE FROM FASP_SYNC_TABLE
   WHERE TABLECODE = 'FASP_T_PUBMENU'
     AND PROVINCE = V_PROVINCE;
  INSERT INTO FASP_SYNC_TABLE
    (TABLECODE, PROVINCE, SRCVERSION, DESVERSION)
    SELECT 'FASP_T_PUBMENU', V_PROVINCE, 0, 1 FROM DUAL;
END;
