DECLARE
  CURSOR T_SESSION IS
    SELECT T2.USERNAME, T2.SID, T2.SERIAL#, T2.LOGON_TIME
    FROM V$LOCKED_OBJECT T1, V$SESSION T2
    WHERE T1.SESSION_ID = T2.SID
    ORDER BY T2.LOGON_TIME;
BEGIN
  FOR T_SESS IN T_SESSION LOOP
    DBMS_OUTPUT.PUT_LINE('[SID] '|| T_SESS.SID || ' [SERIAL#] ' || T_SESS.SERIAL#);
    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION '''||T_SESS.SID||','''||T_SESS.SERIAL#||'''';
  END LOOP;
END;
