CREATE OR REPLACE VIEW V_BAS_NON_TAX_RELATION AS
SELECT *
  FROM (SELECT T.*,
               ROW_NUMBER() OVER(PARTITION BY T.AGENCY_CODE, T.NON_TAX_CODE, T.MOF_DIV_CODE, T.FISCAL_YEAR ORDER BY T.UPDATE_TIME DESC) AS RN FROM BAS_NON_TAX_RELATION T)
 WHERE RN = 1;
